### ISSUE TITLE
No obs-virtual source.dll found in OBS folder

### ISSUE THREAD

**Issue by lucafano04** [CatxFish/obs-virtual-cam#100]
I try to install the software but I can't find any file like obs-virtual source.dll. 
Can you share this file to me? thanks.

**Comment by Mixria** [comment]
Check you're folder "Program Files" and "Program Files (x86).
It's in the plug-in folder on OBS-studio.

Check Obs-VirtualCam.zip download.
Copy/paste the content of the installer doesn't work, and follow the manual installation guide found on GitHub.

**Comment by lucafano04** [comment]
Resolved I install from OBS site:
https://obsproject.com/forum/resources/obs-virtualcam.539/
