### ISSUE TITLE
It closes when enabled Horinzon Flip

### ISSUE THREAD

**Issue by saulotarsobc** [CatxFish/obs-virtual-cam#101]
It closes when enabled Horinzon Flip

![image](https://user-images.githubusercontent.com/23584038/79780978-25cc8880-8313-11ea-94d0-3672237e6f34.png)

![image](https://user-images.githubusercontent.com/23584038/79780984-29600f80-8313-11ea-965a-cede56f5da63.png)

**Comment by Mixria** [comment]
Have you made a search before posting you're problem??
Try that first 😜

This issue is a duplicate of #44

**Comment by saulotarsobc** [comment]
tkns

Em seg., 20 de abr. de 2020 às 16:08, Mixria <notifications@github.com>
escreveu:

**Comment by saulotarsobc** [comment]
> It closes when enabled Horinzon Flip
> 
> ![image](https://user-images.githubusercontent.com/23584038/79780978-25cc8880-8313-11ea-94d0-3672237e6f34.png)
> 
> ![image](https://user-images.githubusercontent.com/23584038/79780984-29600f80-8313-11ea-965a-cede56f5da63.png)
