### ISSUE TITLE
Virus Total detections

### ISSUE THREAD

**Issue by E3V3A** [CatxFish/obs-virtual-cam#102]
How to deal with this? 
Is this a real issue?

* https://www.virustotal.com/gui/file/7ccaeda4e11b010d15b7a0fc6b34226018fa162378bb32f7da5ba25b771fafb4/detection

```
Cybereason  Malicious.04f316
Trapmine    Malicious.high.ml.score
```

**Comment by Technetium1** [comment]
@E3V3A False positives, no cause for concern here. It does not identify with a signature of a known malware, heuristic engines make a guess that something bad is happening.

**Comment by Mixria** [comment]
Might be bacause off the .dll's not being signed.
(Wich costs money to do)

Please mark this as closed @E3V3A

**Comment by E3V3A** [comment]
Yeah I ran some individually and the zip passed... But I don't like it. Signed or not, it should still pass.
