### ISSUE TITLE
"No webcam found" under browser

### ISSUE THREAD

**Issue by cheater** [CatxFish/obs-virtual-cam#125]
I've been trying to use OBS VirtualCam with meet.google.com, and neither Firefox nor Chrome recognize it as a webcam. It simply does not show up, and there is no camera selection. If a USB camera is plugged in, then only that USB device shows up for selection. VirtualCam is started up as described in the doc.

The virtual camera starts up correctly, as can be seen in the OBS log file:

```
18:31:08.042: starting virtual-output on VirtualCam'1'
18:31:37.861: Output 'VirtualOutput': stopping
18:31:37.861: Output 'VirtualOutput': Total frames output: 1788
18:31:37.861: Output 'VirtualOutput': Total drawn frames: 1790
18:31:37.881: virtual-output stop
```

I am on Windows 10, running the latest build from Windows Update.

**Comment by TheTechRobo** [comment]
I have the same problem including in MS Edge.

The webcam was recognized after disabling hardware acceleration but now meet gets stuck on "La camera est en cours de demarrage" (The camera is starting).

**Comment by cheater** [comment]
the fix is to not use this plugin, but instead use the newly added functionality that's integral to OBS. It only came in last month or so. The issue shows up because Windows changed something. The OBS codebase is up to the latest standard, whatever that means.

**Comment by TheTechRobo** [comment]
Ok, thanks :)

I wasn't using 26.0.2 because of "encoder issues" while recording, but I found a video explaining how to fix.
