### ISSUE TITLE
Uninstallation

### ISSUE THREAD

**Issue by baris-inandi** [CatxFish/obs-virtual-cam#136]
I uninstalled virtualcam and obs but the camera devices are still visible. I tried reinstalling and finding a proper uninstallation tool that was intended to be used with virtualcam but couldn't. Also, I tried some manual techniques through the registry editor but it doesn't seem to delete the virtual camera devices from my PC.
[Windows 10 64-bit]

How can I properly uninstall all devices and data associated with virtualcam?
thanks

**Comment by baris-inandi** [comment]
It would be helpful if there is a unins000.exe somewhere inside Program Files directory

**Comment by dispherical** [comment]
I was digging around for the thing and I found a way to uninstall it:
1. Uninstall the main app from control panel (which you have already done)
2. In the folder `C:\Program Files\obs-studio\data\obs-plugins\win-dshow`, run virtualcam-uninstall.bat as an administrator.

**Comment by baris-inandi** [comment]
I am also active in the OBS discord server, they suggested the same thing too. 
I have run the batch file as an admin and just restarted my pc but the virtual camera devices are still there.

**Comment by baris-inandi** [comment]
I managed to do it thanks for the help
