### ISSUE TITLE
gray screen

### ISSUE THREAD

**Issue by Nex4rius** [CatxFish/obs-virtual-cam#15]
I've just installed it and tried to do a google hangout.
I can select the OBS-Camera as webcam but the image is just gray.

I've selected tool and then virtualcam and checked the autostart box.

Do I have to do something else too?

**Comment by CatxFish** [comment]
Try Run OBS as administrator .

**Comment by Nex4rius** [comment]
I tried that and still gray screen.

**Comment by CatxFish** [comment]
May I ask what's the version of OBS you are using?

**Comment by Nex4rius** [comment]
17.0.0
I will update to 18.0.1 and check again.

**Comment by Nex4rius** [comment]
oh wow that completely solved my problem :)
