### ISSUE TITLE
Skype for Business: "Your camera isn't set up, or you're already using it"

### ISSUE THREAD

**Issue by SplatManDK** [CatxFish/obs-virtual-cam#21]
Hi, I just logged an issue on the Skype for Business feedback site, but it seems prudent to point to it from here as well.

https://www.skypefeedback.com/forums/299913-generally-available/suggestions/32883757-error-in-camera-status-detection-your-camera-isn

While the issue may very well be in SFB, one might think that there could be a way to "fix" it here. For example by making a switch (controlled by a reg key perhaps?) or similar option, used in the DirectShow code, that makes the virtual camera report itself as "not occupied" (or whatever the technical attribute is called in real life) by any software. I don't know if this would cause any issues, but I am happy to help test a beta version since the issue is preventing me from using OBS and this virtual cam with SFB.

**Comment by CatxFish** [comment]
I make some modification on version 1.2.1 to avoid this problem on Skype desktop.
I am not sure if is solve the problem on Skype for Business.
Please try it and give some responses.
Thanks

**Comment by Musicalmaestro** [comment]
Hmm, for me with Skype for desktop OBS still does not show up as a camera option like it does for Zoom. Shucks. 
Please keep at it!

**Comment by CatxFish** [comment]
Skype UWP does not accept pure directshow source.
So you have to use Skype desktop or called Skype classic.

You can distinguish them by version number .
UWP version should be 12.x.x and classic version would be 7.x.x or 8.x.x

**Comment by SplatManDK** [comment]
You can also try to run the registration again using the appropriate commands:

Run these in an elevated command prompt (that is: Run as Administrator)
regsvr32 "C:\Program Files (x86)\obs-studio\bin\32bit\obs-virtualsource.dll"
regsvr32 "C:\Program Files (x86)\obs-studio\bin\64bit\obs-virtualsource.dll"

Let us know if that worked.

**Comment by Musicalmaestro** [comment]
ah! Many thanks for this explanation. I much appreciate it. Gotta love technology.

**Comment by Musicalmaestro** [comment]
did not try re-running registration - but installing Skype Classic worked like a charm. :)
Thanks again.
