### ISSUE TITLE
Virtualcam not listed

### ISSUE THREAD

**Issue by MarkBolden** [CatxFish/obs-virtual-cam#22]
Installed with no issues. Registered the DLLs no problem. Select Tools -> virtualcam -> start. I can go to any app (Skype, Hangouts, etc) and it only lists my actual webcam, no virtualcam. My webcam works fine in OBS also. Any ideas?

Win10, Alienware Area51, the latest OBS, the latest VirtualCam.

**Comment by SplatManDK** [comment]
I originally had this issue. Ensure you register both the 32 and 64 bit versions of the components (run it again in an elevated command prompt to be sure). Then restart your machine. Let us know how that works for you. :-)

**Comment by MarkBolden** [comment]
That fixed it! Thanks!!
