### ISSUE TITLE
Failed to register the dll files. 

### ISSUE THREAD

**Issue by wurikiji** [CatxFish/obs-virtual-cam#23]
I  am using Windows 10 professional 64bit. 
When I try to install obs-virtual-cam using installer for windows, the error occurs. 
"Unable to register the DLL/OCS: regsvr32 failed with exit code 0x3." 
I already tried to run the installer with admin and register the dll manually. But it didn't work. 
Does anyone have an idea?

**Comment by CatxFish** [comment]
I can't reproduce same error on my windows 10 laptop. So I have no clue why this happened on some people's environment.

But google search results shows another software also have this issue , especially on Windows 10.
And they gave the following suggestion:
1. Reinstall [Visual C++ Redistributable Packages](https://www.microsoft.com/en-us/download/details.aspx?id=40784)
2. Update Windows 

You can give it a try. 
And If anyone have solved this problem before, please share you experience , that will be helpful .

**Comment by wurikiji** [comment]
@CatxFish Thanks for your quick reply. I will try your suggestions and others. 
If I solve this problem, I will post it.

**Comment by mumblyOMOD** [comment]
I had the same problem when I was testing out some different webcam software. It ended up being a really silly problem. I'd uninstalled obs-studio when I was testing (and forgot that I'd uninstalled it) and got this error repeatedly. Once I reinstalled obs-studio the install went perfectly.

**Comment by SplatManDK** [comment]
Just a quick reminder: Remember that the command prompt has to be elevated (run as Administrator) in order to register components.

**Comment by Helmsman2001** [comment]
Im logged in as an admin and the command prompt will not open as admin

**Comment by GenesisFR** [comment]
I had the same problem on OBS Studio 21.0.1. I had removed all 32-bit files from my OBS folder since I'm only using 64-bit executable.

It turns out that to register obs-virtualsource.dll, you just need to have the following 32-bit DLLs shipped with OBS:

```
avutil-55.dll
swscale-4.dll
```

Before doing this, OBS-Camera was not showing up on Discord. It seems to work fine now after a quick test.

**Comment by wurikiji** [comment]
@GenesisFR @mumblyOMOD 
Thank you for your help. Both solutions worked properly. 
Close this issue.

**Comment by JoshMLeslie** [comment]
Installing the C++ Redis packages as CatxFish mentions above fixed it for me - I'm running windows 10 pro and needed both the x64 **AND** x86 versions from the microsoft site. Windows update never hurts either but didn't seem to affect anything. I also got a firewall warning, but didn't seem to affect anything so far - haven't tried streaming yet, but everything else seems good.
