### ISSUE TITLE
Issue installing 

### ISSUE THREAD

**Issue by Chuckyzee** [CatxFish/obs-virtual-cam#27]
Catxfish, I read through all the comments and issues and couldn't find much help on the issue I am having.  I tried the installer for obs-virtual cam and it would not install.  I switched over to administrator on windows 10 and tried again.  I keep getting the same error.  

C:/Program Files
(x86)\obs-studio\bin\64bit\obs-virtualsource.dll

Unable to register the DLL/OCX: RegSvr32 failed with exit code 0x3

I also tried to install the zip file in the OBS directory and the go through the CMD prompt to register the DLL files both 32 and 64bit and was not successful.

Please advise.  I am needing this badly for pulling green screen from OBS to hangouts and other things.

Respectfully,

Chuckyzee

**Comment by CatxFish** [comment]
Do you read [this issue](https://github.com/CatxFish/obs-virtual-cam/issues/23) ?
Lack of avutil-55.dll,swscale-4.dll in the directory will cause same problem .

**Comment by Chuckyzee** [comment]
I have no idea how I missed that one.  Must have been 3am.  

The reinstall of the C++ and windows update worked.  Thanks so much.

Chuckyzee
