### ISSUE TITLE
Use scene as source

### ISSUE THREAD

**Issue by dmratcliffe** [CatxFish/obs-virtual-cam#29]
It would be nice to be able to use the a scene as the source for the virtual camera to display, this would be useful for things like kinect greenscreen and ect.

Is this possible even?

**Comment by SplatManDK** [comment]
You can alteady do this with OBS Studio or Streamlabs, since multiple sources can be mixed. What are you trying to do, that's not already possible? :-)

**Comment by CatxFish** [comment]
I guess what you want is output virtual camera based on a source not whole canvas , but this feature has not implement yet.

**Comment by LanceLake** [comment]
I am using 2.0.4 and there is no option to select a scene or source that I can see.
