### ISSUE TITLE
Linux support/version

### ISSUE THREAD

**Issue by StripedMonkey** [CatxFish/obs-virtual-cam#3]
I'm actually trying to figure out how to do something like this on linux and without looking at the code I was wondering if it would take much work to set this up on linux.

**Comment by CatxFish** [comment]
I am not sure how can I help you.
You want to write linux plugin yourself or it's a feature request?

**Comment by StripedMonkey** [comment]
I was doing it as a feature req however I found a kernel module for Linux that makes a dummy webcam that you can basically just pipe video into so there is no need now. But thanks anyways

**Comment by doakey3** [comment]
@StripedMonkey, would you mind telling me how you did this?

**Comment by StripedMonkey** [comment]
Basically there is a kernel module that I forget the name of rn (I'll look at what it is when I get home) iirc it creates a webcam in /dev and I used some roundabout way to have ffmpeg spit out a raw stream that was piped into the file and you should be able to read it like a normal webcam

**Comment by SplatManDK** [comment]
It sounds nifty. But would that work without a recompile? Most ordinary users need a solution that can be installed script and run in user space. 

My knowledge is admittedly limited, but it sounds like your approach is firmly entrenched in "expert land".

**Comment by doakey3** [comment]
I found it pretty soon after asking. I used v4l2loopback. I'm using Arch Linux, so I installed it with:

    yaourt -S v4l2loopback-dkms-git

Then I loaded it with

        modprobe v4l2loopback

Then I used ffmpeg to do the dummy web cam. Note that I had to use /dev/video1 because /dev/video0 is my actual webcam:

    ffmpeg -f alsa -i pulse -f x11grab -r 15 -video_size 1280x720 -i :0.0+0,0 -vcodec rawvideo -pix_fmt yuv420p -threads 0 -f v4l2 /dev/video1

You can change the :0.0+0,0 part to offset what part of the screen gets included into the dummy webcam.

**Comment by StripedMonkey** [comment]
@SplatManDK not at all, the Linux kernel is modular by design and kernel modules can be loaded and unloaded at will without restarting anything. The most complicated thing is getting ffmpeg to output properly. The kernel module is an install and forget kinda thing.
