### ISSUE TITLE
Won't install on a naked windows 10 install

### ISSUE THREAD

**Issue by walduino** [CatxFish/obs-virtual-cam#30]
This plugin worked as a charm before yesterday....
Had my only windows device crash its HDD yesterday, Reinstalled windows 10 home; installed OBS Studio; then the plugin. But when i try to register the dll i get an error:

The module "C:\Program Files
(x86)\obs-studio\bin\32bit\obs-virtual source.dll' failed to load.

Make sure the binary is stored at the specified path or debug it to
check for problems with the binary or dependent DLL files.

The specified module could not be found.

The path autocompletes so i doubt the actual dll is the issue ....Any ideas ?

**Comment by CatxFish** [comment]
Latest this error can be solved by install [Visual C++ Redistributable Packages](https://www.microsoft.com/en-us/download/details.aspx?id=40784)

I'll do some fix recently.

**Comment by walduino** [comment]
Thanks FIXED !
