### ISSUE TITLE
OBS-camera isn't showing up

### ISSUE THREAD

**Issue by Hanjocl** [CatxFish/obs-virtual-cam#32]
I have a problem where discord doesn't recognize the virtual cam.
I used the installer to instal the virtual cam.

I've reinstalled obs, discord and the virtual cam multiple times. I also updated windows.
I've also tried to instal older versions of obs and te virtual cam.

but nothing seems to help to show the virtual cam as a webcam.

**Comment by CatxFish** [comment]
Do you get the same result on other software? Or only on discord?

**Comment by Hanjocl** [comment]
Yes, I have tried Skype and VLC player but they also don't see a OBS-camera.

**Comment by CatxFish** [comment]
That seems you don't successfully register camera for some reason.
Check whether "C:\Program Files (x86)\obs-studio\bin\32bit\obs-virtualsource.dll " exist or not.
You might need to register it manually.

**Comment by Hanjocl** [comment]
That worked!!
I don't know what I've done different but first I got errors when I tried to register the file.

Thanks for responding so quick

**Comment by breathlessblizzard** [comment]
Hello,
I'm having a similar issue, except the virtual camera fails to show up _only_ in Discord, it works fine in google hangouts and vlc. I've checked that the DLL's are there. Let me know if I should make a new issue; otherwise, any advice for getting this to work?
