### ISSUE TITLE
Problem with Skype 7.xx & 8.xx

### ISSUE THREAD

**Issue by KovalevArtem** [CatxFish/obs-virtual-cam#33]
I did everything according to the instructions:

- Unzip OBS-VirtualCam.zip and put it to your obs-studio install folder.
- Run CMD as Administrator and register 64bit directshow source

My result:
(I apologize for the Russian interface of the programs)

![1](https://user-images.githubusercontent.com/36500228/44959730-e3ff8c00-aefb-11e8-88aa-48e333c9dc23.png)
Skype 7.xx only sees a physically connected webcam...

![skype 8](https://user-images.githubusercontent.com/36500228/44959737-07c2d200-aefc-11e8-9815-51192146a988.png)
Skype 8.xx only sees a physically connected webcam...

![video capture device](https://user-images.githubusercontent.com/36500228/44959740-0f827680-aefc-11e8-913e-6dbcde834ec0.png)
OBS Video Capture Device

How can I fix it?

**Comment by CatxFish** [comment]
Sorry this is issue which lack of 32bit components, install 32bit obs or go to obs forum for help, I can’t make an update because I am in hospital, I will fix it when I get better.

**Comment by ROBERT-MCDOWELL** [comment]
hope you will heal soon. GOD bless you and your family

**Comment by CatxFish** [comment]
Just a notice , this problem should have been fixed in 2.0.2 . 
And I am getting better, thank for your kind concern.

**Comment by KovalevArtem** [comment]
Still need to fix errors in readme.MD ...
On the PC x64 another way to install the OBS ...

**Comment by CatxFish** [comment]
OK, I fix it.
