### ISSUE TITLE
downscale in chrome

### ISSUE THREAD

**Issue by jnblanchet** [CatxFish/obs-virtual-cam#5]
Hey, thanks for this amazing obs-plugin!

I'm trying to convert an NDI video feed into a direct show camera through OBS, and use it for WebRTC conference calls. My goal is to use the OBS feed in a browser application, e.g. [this](https://webrtc.github.io/samples/src/content/devices/input-output/) WebRTC demo.

It works well at lower resolution (1024x768). But when I increase it to something like 2550x1440, Chrome downscales the frames using a nearest neighbor interpolation, and ruins the video quality.

Interestingly enough, VLC gives me a clean preview of the video feed. Also, It works well in Chrome when using [NDI Transmit](https://www.newtek.com/software/transmit/) which converts an NDI feed into a directshow camera (which is essentially the same as this plug-in, but without the OBS flexibility). This leads me to think it's a problem with either the plug-in or OBS.

Any ideas on how to fix this? Thank you!

**Comment by CatxFish** [comment]
Directshow interface can't not change resolution when it is using.
Do you reopen RTC or chrome after you change OBS resolution setting?
If not, directshow interface should downscale to 1024x768.

**Comment by jnblanchet** [comment]
You are right!

It turns out this is a webRTC issue. If I force the resolution in my JavaScript, it works. Thanks!
