### ISSUE TITLE
Windows 1803 do not work

### ISSUE THREAD

**Issue by Damianuscz** [CatxFish/obs-virtual-cam#52]
Virtual cam do not work in new Windows update :(

**Comment by Technetium1** [comment]
@Damianuscz You should be using version 1809! [https://www.microsoft.com/en-us/software-download/windows10](https://www.microsoft.com/en-us/software-download/windows10)

**Comment by Damianuscz** [comment]
@Technetium1 my bad. I use last version of windows 1809 build 17763.475 version.

Same problem

**Comment by Technetium1** [comment]
Can you give more details as to what does not work specifically?

**Comment by Damianuscz** [comment]
My bad. Virtual cam did not work only in updated MS camera app and i think html5 (not webapp) version of Skype. When i donwload dekstop version it is ok.

But i have new problem :D

https://github.com/CatxFish/obs-virtual-cam/issues/44
