### ISSUE TITLE
can't output for portrait resolution on Discord(and Skype)

### ISSUE THREAD

**Issue by negipoyoc** [CatxFish/obs-virtual-cam#61]
First, thank you for the great plugin.

I think the resolution setting is OBS compliant. (The image specifies a size of 1080 x 1920.)

![image](https://user-images.githubusercontent.com/31283418/68124111-e3c0ad80-ff51-11e9-9d51-d13f3f345480.png)

However, the portrait resolution canvas is specified and output to 1080x1920 display(with full screen Discord ), but the output is like this.

![68124380-9bee5600-ff52-11e9-8e21-ae0ff3a2778b](https://user-images.githubusercontent.com/31283418/68124533-fa1b3900-ff52-11e9-8f70-66b3f1678e72.png)

The image appears to be first output at 1920 * 1080 and then compressed to a 9: 16 image.

Is this because Discord doesn't support the resolution? I would like to know if this is a problem with the OBS Virtual Cam because the same thing happened with Skype.

Thank you.

**Comment by CatxFish** [comment]
The policy of this plugin is if the 3rd party software don't accept the default resolution then resize to the resolution they ask for , so it's much likely they don't directly support portrait resolution.

**Comment by negipoyoc** [comment]
Hi, I'm sorry for late reply.
I understood the policy, Thank you.
