### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by cobafesbuk** [CatxFish/obs-virtual-cam#7]
Hi, is there any tutorial how to use this? I'm new to streaming and don't really know about it.
I'm trying to use OBS to stream in this web https://live.fc2.com/.

The OBS-Camera is detected successfully and allowed in the flash. But the screen just shows grey background.

I've tried:
1. Run OBS as Admin
2. Run both OBS 32 and 64 bit
3. Start Streaming(nothing happens)
4. Start Recording(only save a video)

Screenshots:
http://i.imgur.com/g32wNGZ.jpg
http://i.imgur.com/emYkOcP.jpg
http://i.imgur.com/1EWUgcO.jpg

**Comment by CatxFish** [comment]
Gray picture means the camera do not connect to OBS successfully , Have you ever try other software connecting like VLC?  

By the way , fc2 works fine on my laptop . 
[http://i.imgur.com/5A43X7V.png](http://i.imgur.com/5A43X7V.png)

**Comment by cobafesbuk** [comment]
Thank you it's working now :)
I must have missed that instruction somewhere..
