### ISSUE TITLE
Zoom windows application fails to activate camera, while it works with Skype on the same machine

### ISSUE THREAD

**Issue by Dzoge** [CatxFish/obs-virtual-cam#78]
Virtual camera works well with Skype but I cannot make it work with the zoom application on Windows 10.

Zoom application gives the error saying:
Cannot start video
Failed to start the video camera. Please select another video camera in Settings.

I tried both 64 bit obs and 32 bit obs, latest version.
I used the Latest installer of virtual cam:
https://github.com/CatxFish/obs-virtual-cam/releases/tag/2.0.4

Could anyone please help me troubleshoot the issue?

**Comment by beren1hand** [comment]
I'm having a similar issue with the version 4 of Zoom, but version 3 is working fine. Try installing this and see if it helps you:

https://chrome.google.com/webstore/detail/zoom/hmbjbjdpkobdjplfobhljndfdfdipjhg/related?hl=en

**Comment by dotex3** [comment]
It seems to be a compatibility issue with Zoom. If you look at the Zoom directory (likely C:\Users\[yourname]\AppData\Roaming\Zoom) on your PC there is a file labeled dllsafecheck.txt. It shows that OBS VirtualCam is "failing verification." Not sure if there is a way to bypass the check in order to use the cam in Zoom. Hopefully, someone can use this info!

**Comment by QueenSayel** [comment]
I am having the exact same issue even though it had worked up until a few hours ago. I am puzzled.

**Comment by dotex3** [comment]
Update: I've reached out to Zoom and I'm awaiting a reply. If you install using MSI there is a dll named dllsafecheck.dll. I am not an expert so I don't know if there is a way to disable it.

The link provided by @QueenSayel is working with VirtualCam. Thanks for sharing, I couldn't find an old version anywhere else! You can also use Zoom through your browser by clicking start/join on the website, choosing click here on "If nothing prompts from browser, click here" and then refusing to let Zoom launch, this should bring up a prompt to use Zoom in your browser. Hope this helps!

**Comment by black-zone-1000** [comment]
Unbelievable.
I spent always a full day trying everything to solve and it turns out this is a damm "feature" in Zoom that performs "dllsafecheck"...
Thanks @QueenSayel  and @beren1hand  both version 4.6.7 or using the chrome plugin solves the issue

**Comment by sweetasdude** [comment]
Much appreciated, same issue, verified that the link QueenSayel solved my problem too. Great work, been tearing my hair out.

**Comment by schmlandinksy** [comment]
> I am having the exact same issue even though it had worked up until a few hours ago. I am puzzled.
> 
> EDIT: Version 4.6.8 is the cause. They must have changed something. I still had the link to the previous version in my download manager history. Upon installing 4.6.7 everything is working again.
> 
> https://d11yldzmag5yn.cloudfront.net/prod/4.6.18176.0301/ZoomInstaller.exe

Thank you!! I have spent all day trying to troubleshoot it, assuming it was an issue with OBS. This finally fixed it for me.

**Comment by notr1ch** [comment]
I made a shitty patch that replaces the problematic `DllSafeCheck.dll` file installed by the newest version of Zoom with a dummy one that does nothing. Use at own risk etc.

https://r-1.ch/ok_zoomer.zip

Source code: `__declspec(dllexport) void HackCheck (void) { return; }`

**Comment by HandSonic** [comment]
> 我制作了一个糟糕的补丁程序，用`DllSafeCheck.dll`无能为力的虚拟人替换了最新版本的Zoom安装的有问题的文件。使用风险自负。
> 
> https://r-1.ch/ok_zoomer.zip
> 
> 源代码： `__declspec(dllexport) void HackCheck (void) { return; }`

Thanks, this works.

**Comment by nPrevail** [comment]
Does anyone happen to have the Mac version of Zoom 4.6.18176.0301?

**Comment by dkapz** [comment]
thanks for the 4.6.7 tip!

**Comment by SwanTron207** [comment]
> I made a shitty patch that replaces the problematic `DllSafeCheck.dll` file installed by the newest version of Zoom with a dummy one that does nothing. Use at own risk etc.
> 
> https://r-1.ch/ok_zoomer.zip
> 
> Source code: `__declspec(dllexport) void HackCheck (void) { return; }`

This worked for me as well. Thank you for the stop gap.

**Comment by aoanla** [comment]
I tried to open a support ticket with Zoom about this but no response yet [has anyone else tried this approach?]

**Comment by itsamaik** [comment]
> I made a shitty patch that replaces the problematic `DllSafeCheck.dll` file installed by the newest version of Zoom with a dummy one that does nothing. Use at own risk etc.
> 
> https://r-1.ch/ok_zoomer.zip
> 
> Source code: `__declspec(dllexport) void HackCheck (void) { return; }`

Worked for me, v4.6.9. Great filename btw.

**Comment by KovalevArtem** [comment]
![image](https://user-images.githubusercontent.com/36500228/78303849-31b00080-7546-11ea-8a8a-43bf72716cfa.png)
I do not risk updating ...
Last update does not solve this problem?

**Comment by MikaelFerland** [comment]
> ![image](https://user-images.githubusercontent.com/36500228/78303849-31b00080-7546-11ea-8a8a-43bf72716cfa.png)
> I do not risk updating...
> Last update does not solve this problem?

No even with this update, it's still not working.

**Comment by EMREOYUN** [comment]
> ![image](https://user-images.githubusercontent.com/36500228/78303849-31b00080-7546-11ea-8a8a-43bf72716cfa.png)
> I do not risk updating...
> Last update does not solve this problem?

Do not update, both versions blocks obs-virtualcam

**Comment by itsamaik** [comment]
I am on version 4.6.9(19253.0401) and encountered this issue. The ok_zoomer.zip patch as mentioned above still works on this version. So in that sense you could update and patch Zoom, in case you need to update for some reason.

**Comment by MajorMalarky** [comment]
I just got off the phone with Zoom, and here is part of the correspondance.
"Hello, thank you for contacting Zoom Support! It sounds like the update is definitely the cause then. Also had a few customers today saying that Logitech cameras were also not working properly. But for OBS, I will gladly also bring this to engineering's attention."
"See if rolling back to this version works: https://zoom.us/client/4.6.19178.0323/ZoomInstaller.exe"
I mentioned the version shared above, and here is the link to Zoom to get it.
"https://zoom.us/client/4.6.18176.0301/ZoomInstaller.exe" 
Which is just changing the middle numbers.
They suggested rolling back until they have this fixed.

**Comment by stock90** [comment]
> I just got off the phone with Zoom, and here is part of the correspondance.
> "Hello, thank you for contacting Zoom Support! It sounds like the update is definitely the cause then. Also had a few customers today saying that Logitech cameras were also not working properly. But for OBS, I will gladly also bring this to engineering's attention."
> "See if rolling back to this version works: https://zoom.us/client/4.6.19178.0323/ZoomInstaller.exe"
> I mentioned the version shared above, and here is the link to Zoom to get it.
> "https://zoom.us/client/4.6.18176.0301/ZoomInstaller.exe"
> Which is just changing the middle numbers.
> They suggested rolling back until they have this fixed.
Even using 4.6.7 (18176.0301), Zoom is forcing me to update to the latest version (4.6.19253.0401) which I don't want. When prompted to update, Clicking on the Close box (not even clicking on "Later") doesn't stop the update happening after I restart.

Anyone have any idea how to turn off updates?

**Comment by mbax** [comment]
To stop the automatic update on restart, at least on Windows:

While the client is running, it will automatically download the installer for the update. Before next start, find the Zoom folder (on Windows you can just navigate to `%APPDATA%\Zoom`) and delete the folder named with the update number, containing the installer files. Currently that folder is `4.6.19253.0401`

**Comment by DiegoPerez1441** [comment]
> I am having the exact same issue even though it had worked up until a few hours ago. I am puzzled.
> 
> EDIT: Version 4.6.8 is the cause. They must have changed something. I still had the link to the previous version in my download manager history. Upon installing 4.6.7 everything is working again.
> 
> https://d11yldzmag5yn.cloudfront.net/prod/4.6.18176.0301/ZoomInstaller.exe

For me it does recognize the obs-virtual-cam, but it displays a grey screen. I'm using 4.6.9.
Note: I'm using the 64-bit version and obs-virtual-cam is on.

**Comment by EMREOYUN** [comment]
> > I am having the exact same issue even though it had worked up until a few hours ago. I am puzzled.
> > EDIT: Version 4.6.8 is the cause. They must have changed something. I still had the link to the previous version in my download manager history. Upon installing 4.6.7 everything is working again.
> > https://d11yldzmag5yn.cloudfront.net/prod/4.6.18176.0301/ZoomInstaller.exe
> 
> For me it does recognize the obs-virtual-cam, but it displays a grey screen. I'm using 4.6.9.
> Note: I'm using the 64-bit version and obs-virtual-cam is on.
> 
> Update: Version 4.6.7 worked perfect for me. They "fixed security bugs", I'm wondering if we can patch this new version.

It's already patched, use ok zoomer patch in here:


> I made a shitty patch that replaces the problematic `DllSafeCheck.dll` file installed by the newest version of Zoom with a dummy one that does nothing. Use at own risk etc.
> 
> https://r-1.ch/ok_zoomer.zip
> 
> Source code: `__declspec(dllexport) void HackCheck (void) { return; }`

**Comment by PatrickHXXVIII** [comment]
> I made a shitty patch that replaces the problematic `DllSafeCheck.dll` file installed by the newest version of Zoom with a dummy one that does nothing. Use at own risk etc.
> 
> https://r-1.ch/ok_zoomer.zip
> 
> Source code: `__declspec(dllexport) void HackCheck (void) { return; }`

I have been thus far unable to get this to work, how should it be enabled?

**Comment by robmc1** [comment]
Ok_zoomer fix is being flagged as a virus by defender.

https://i.imgur.com/s4bIJPr.png

**Comment by DiegoPerez1441** [comment]
Zoom automatically updates? How do I disable besides reinstalling every time I open Zoom.

**Comment by gvhagopian** [comment]
> Ok_zoomer fix is being flagged as a virus by defender.
> 
> https://i.imgur.com/s4bIJPr.png

I got the same windows defender flag. Building my own DLL that exports the same dummy HackCheck function that @notr1ch posted did not work. Any possibility we could get the full source code?

**Comment by EMREOYUN** [comment]
> > I made a shitty patch that replaces the problematic `DllSafeCheck.dll` file installed by the newest version of Zoom with a dummy one that does nothing. Use at own risk etc.
> > https://r-1.ch/ok_zoomer.zip
> > Source code: `__declspec(dllexport) void HackCheck (void) { return; }`
> 
> I have been thus far unable to get this to work, how should it be enabled?

Just open exe file and this thing patches that dll.

**Comment by dernyn** [comment]
> Ok_zoomer fix is being flagged as a virus by defender.
> 
> https://i.imgur.com/s4bIJPr.png

Yes but is not a virus, apparently it was reported or posted by someone invested in the DllSafeCheck.dll, most-likely Zoom, Corp.
the zip contains a executable that renames the old dll and creates a new one with a fake DLL export function used by the new Zoom version.
here is what that said dll & function looks like:
https://i.imgur.com/uKukqvQ.png

you can tell windows defender or whatever anti-virus/malware software to allow the file/download and it's execution...check your Windows Defender on the Windows Security section in Win10

**Comment by EMREOYUN** [comment]
> > Ok_zoomer fix is being flagged as a virus by defender.
> > https://i.imgur.com/s4bIJPr.png
> 
> Yes but is not a virus, apparently it was reported or posted by someone invested in the DllSafeCheck.dll, most-likely Zoom, Corp.
> the zip contains a executable that renames the old dll and creates a new one with a fake DLL export function used by the new Zoom version.
> here is what that said dll & function looks like:
> https://i.imgur.com/uKukqvQ.png
> 
> you can tell windows defender or whatever anti-virus/malware software to allow the file/download and it's execution...check your Windows Defender on the Windows Security section in Win10

Which program you use to inspect dll's?

**Comment by gvhagopian** [comment]
> Yes but is not a virus, apparently it was reported or posted by someone invested in the DllSafeCheck.dll, most-likely Zoom, Corp.

I emailed the copy of DllSafeCheck.dll I compiled myself and it is not flagged. I'd recommend people compile it themselves rather than running a random .exe someone uploaded. Maybe it is a false positive, but no reason to take the chance.

**Comment by DiegoPerez1441** [comment]
> > Yes but is not a virus, apparently it was reported or posted by someone invested in the DllSafeCheck.dll, most-likely Zoom, Corp.
> 
> I emailed the copy of DllSafeCheck.dll I compiled myself and it is not flagged. I'd recommend people compile it themselves rather than running a random .exe someone uploaded. Maybe it is a false positive, but no reason to take the chance.

How would you compile the .exe? I'm running Windows 10 64-bit and I have Visual Studio.

**Comment by dernyn** [comment]
The problem is that it was not just some random person who compiled it — it was Richard Stanway one of the very individuals behind this plugin for OBS and the creators of OBS Studio,  go back to the original part of his post https://github.com/CatxFish/obs-virtual-cam/issues/78#issuecomment-605386370


This dll restriction issue on Zoom affects many different DirectShow virtual cameras and audio software , including Logitech software.

**Comment by Alyssa3467** [comment]
> I made a shitty patch that replaces the problematic `DllSafeCheck.dll` file installed by the newest version of Zoom with a dummy one that does nothing. Use at own risk etc.
> 
> https://r-1.ch/ok_zoomer.zip
> 
> Source code: `__declspec(dllexport) void HackCheck (void) { return; }`

It seems that this patch somehow breaks screen sharing. Any attempt to start screen sharing results in a dialog box that says "Screen sharing has failed to start. Please try again later. Error Code 105035"

**Comment by robmc1** [comment]
> > I made a shitty patch that replaces the problematic `DllSafeCheck.dll` file installed by the newest version of Zoom with a dummy one that does nothing. Use at own risk etc.
> > https://r-1.ch/ok_zoomer.zip
> > Source code: `__declspec(dllexport) void HackCheck (void) { return; }`
> 
> It seems that this patch somehow breaks screen sharing. Any attempt to start screen sharing results in a dialog box that says "Screen sharing has failed to start. Please try again later. Error Code 105035"

At least OBS can have display capture as a scene. That still works as part of a virtualcam.
https://i.imgur.com/iw8cyfU.png

**Comment by notr1ch** [comment]
> > Yes but is not a virus, apparently it was reported or posted by someone invested in the DllSafeCheck.dll, most-likely Zoom, Corp.
> 
> I emailed the copy of DllSafeCheck.dll I compiled myself and it is not flagged. I'd recommend people compile it themselves rather than running a random .exe someone uploaded. Maybe it is a false positive, but no reason to take the chance.

I contacted Microsoft, they've removed the false positive in Windows Defender.

> > I made a shitty patch that replaces the problematic `DllSafeCheck.dll` file installed by the newest version of Zoom with a dummy one that does nothing. Use at own risk etc.
> > https://r-1.ch/ok_zoomer.zip
> > Source code: `__declspec(dllexport) void HackCheck (void) { return; }`
> 
> It seems that this patch somehow breaks screen sharing. Any attempt to start screen sharing results in a dialog box that says "Screen sharing has failed to start. Please try again later. Error Code 105035"

This is a known problem unfortunately, Zoom does a scan of the DLLs before starting screen sharing and refuses to let you screen share if they are not signed by Zoom.

**Comment by aoanla** [comment]
As a workaround - I've just confirmed that using the OBS NDI plugin (which lets you export your OBS output over the NewTek "Network Device Interface) from here: https://obsproject.com/forum/resources/obs-ndi-newtek-ndi™-integration-into-obs-studio.528/ and NewTek's free NDI Tools, from here: 
https://ndi.tv/tools/

works, even within the same PC. (You need to enable OBS NDI output in the Tools menu... and then launch the "VirtualInput" tool from the NDI Toolkit - it will add a little notification bar widget which you can use to point it at the new NDI output. The VirtualInput will then appear to Zoom (and Skype etc) as a new camera device - and whatever it does differently seems to be acceptable to Zoom, as it was loaded perfectly.)

**Comment by KovalevArtem** [comment]
> Screen sharing has failed to start. Please try again later. Error Code 105035

![image](https://user-images.githubusercontent.com/36500228/78563805-3580a300-7824-11ea-9df5-6e9e616ddb0b.png)
@notr1ch This problem really exists.

**Comment by LordAshes** [comment]
Another solution that is somewhat round-about but seems to work is to proxy the OBS VirtualCam through another program. For example, the free version of ManyCam. It is a really round-about way to do it but it worked for me with Zoom.

Basically I opened OBS, started the VirtualCam. Then I opened ManyCam where I selected the corresponding OBS Camera as the source. In ZOOM, I selected the virtual ManyCam camera instead of the OBS Camera.

Please note that depending on the proxy application used, the quality of the video may be downgraded. For example, the free version of ManyCam supports only 720p even if the source (OBS Camera) is using a higher resolution.

It is not an ideal solution but works in a pinch if you don't want to much around with replacing Zoom DLLs.

**Comment by black-zone-1000** [comment]
Seems to me that the best solution will be to find out what restrictions did Zoom apply and then change the OBS virtual cam code so it will comply with those restrictions.
From the name of the DLL I can only assume that the restrictions are security-related and that the OBS virtual cam performs unsafe calls which are blocked by Zoom.
Anybody had luck contacting Zoom and asking for more details?

**Comment by black-zone-1000** [comment]
Found this interesting article:
https://blog.syscall.party/post/tampering-with-zooms-anti-tampering-library/

It could be that the only thing which is really required is that the DLLs OBS virtual cam uses be signed. 

Does anybody have a code signing certificate?

**Comment by bekriebel** [comment]
@black-zone-1000 I did try signing the dlls with a self-signed certifcate that is authorized on my machine. That did not seem to fix it.

However, I can confirm that downgrading the plugin to https://github.com/CatxFish/obs-virtual-cam/releases/tag/2.0.2 does resolve the issue with zoom. I checked, and those DLLs are not signed, so the issue appears to be somewhere else.

**Comment by KovalevArtem** [comment]
> OBS Studio 25.0.4

Hmmmm. Only the OBS-VirtualCam 2.0.4 plugin works on versions of OBS 24.x.x and OBS 25.x.x and higher, the versions of the plugin below did not work ...

**Comment by chuyskywalker** [comment]
> add



> The VirtualInput will then appear to Zoom (and Skype etc) as a new camera device - and whatever it does differently seems to be acceptable to Zoom, as it was loaded perfectly.)

Not only that, it ALSO carries the captured audio over as an NDI input so you get the right audio output!

**Comment by eyaldr3333** [comment]
> As a workaround - I've just confirmed that using the OBS NDI plugin (which lets you export your OBS output over the NewTek "Network Device Interface) from here: [https://obsproject.com/forum/resources/obs-ndi-newtek-ndi™-integration-into-obs-studio.528/](https://obsproject.com/forum/resources/obs-ndi-newtek-ndi%E2%84%A2-integration-into-obs-studio.528/) and NewTek's free NDI Tools, from here:
> https://ndi.tv/tools/
> 
> works, even within the same PC. (You need to enable OBS NDI output in the Tools menu... and then launch the "VirtualInput" tool from the NDI Toolkit - it will add a little notification bar widget which you can use to point it at the new NDI output. The VirtualInput will then appear to Zoom (and Skype etc) as a new camera device - and whatever it does differently seems to be acceptable to Zoom, as it was loaded perfectly.)

it wokrs perfectly. tnx.

**Comment by KovalevArtem** [comment]
![image](https://user-images.githubusercontent.com/36500228/78781827-9d142b00-79a9-11ea-9344-653e841ec2fd.png)
Latest ZOOM Update Fixes Virtual Camera Problem!

**Comment by aoanla** [comment]
Confirming that 4.6.20033.0407 fixes the issue (although if you use OBS VirtualCam as a source, the "Video" preferences pane in Zoom becomes weirdly laggy - it took 5 or 6 seconds for it to recognise that I unticked "mirror my video").

**Comment by morrisonbrett** [comment]
Confirmed. Latest Zoom is working with obs-virtual-cam v2.0.4.

**Comment by EMREOYUN** [comment]
> ![image](https://user-images.githubusercontent.com/36500228/78781827-9d142b00-79a9-11ea-9344-653e841ec2fd.png)
> The latest ZOOM update fixes a virtual camera issue.

Tested, this version have no issues with obs-virtualcam.

**Comment by LordAshes** [comment]
Confirmed. Works like a charm with Zoom update.

**Comment by KovalevArtem** [comment]
@Dzoge or @CatxFish 
Close issues

**Comment by sudhaker** [comment]
Seems like the same issue came back in Zoom 5.0.x 😖 which is a forced update as older version will cease to work at the month-end.
