### ISSUE TITLE
Screen is flipped?

### ISSUE THREAD

**Issue by cobafesbuk** [CatxFish/obs-virtual-cam#8]
Hi, I just noticed that the screen/camera is flipped on Google Hangouts and https://meet.jit.si/.
Is this bug or intended? It's not really a problem for me, I just want to report it.
http://i.imgur.com/tXxZzWR.jpg

**Comment by CatxFish** [comment]
I Have tried Google Hangouts by a real webcam and find some software always flip webcam image to assure you can react to your viewer in the same direction. 
The Virtual camera do nothing about this , but I will consider if is necessary to implement a flip feature.
Thanks for your report.

**Comment by CatxFish** [comment]
By the way , If you need to flip virtual-cam now , please use obs built-in horizontal flip effect.

**Comment by cobafesbuk** [comment]
I see. I didn't know about that. 
Thank you for the explanation! :)
