### ISSUE TITLE
OBS-audio device didn't found

### ISSUE THREAD

**Issue by ilmatematico** [CatxFish/obs-virtual-cam#9]
I've experienced that obs-audio device doesn't appear in any device list (such as chrome mic, firefox, windows rec device) where instead obs-video is correctly displayed.
I can access it only via VLC

![image](https://user-images.githubusercontent.com/6051870/30207857-42174f2a-9491-11e7-9fb8-7eac54f770b3.png)

**Comment by CatxFish** [comment]
Unfortunately it is normal that you can't see virtual audio in the device list , because directshow interface won't be recognized as a microphone.
Only software using directshow interface can access audio data , just like VLC.
It will need to write a fake audio driver and  it's still planning.
