### ISSUE TITLE
[Installer] [Bug] Installer is installing to improper location

### ISSUE THREAD

**Issue by Fenrirthviti** [CatxFish/obs-virtual-cam#91]
Due to the increase in users wanting to use virtual cameras with services like Skype and Zoom, we have had an influx of users installing this plugin come through the OBS discord and support chats.

They are having difficulties finding the installer in the first place (which is confusing to me, but another matter), but when they do the installer sometimes installs in the incorrect folder, causing the plugin to fail to load. The installer does not allow you to provide an install location, meaning that remediation for this issue is extremely difficult.

**Comment by Mixria** [comment]
Use the manual install instruction instead. (Copy/paste from zip file)
Testet in Zoom on Win 10 1909  with OBS 25.0.4 x64 and OBS-VirtualCam 2.0.4

**Comment by E3V3A** [comment]
See my better instructions here:

* https://github.com/alievk/avatarify/issues/94

**Comment by Fenrirthviti** [comment]
This is not about manually installing. This is about the installer being provided that does not allow for verification of the directory that OBS Studio is installed to, resulting in it being installed in the wrong place. I'm not having this issue or looking for a workaround, I am reporting an issue with the installer that should be fixed. I appreciate the attempts to help, but you're missing the point of the report.

Either way it seems that CatxFish is no longer active, so I'm just going to close this as it's unlikely to be fixed.
