### ISSUE TITLE
Horizontal Flip lead OBS to crash.

### ISSUE THREAD

**Issue by EloiStree** [CatxFish/obs-virtual-cam#98]
![image](https://user-images.githubusercontent.com/20149493/79367292-e63a2100-7f4d-11ea-856d-92d9d5242346.png)

Hello, 
I am surprise that during Cov19 your plug-in make huge sens to teachers across the world.
But it seems that everybody commenting on the Youtube videos have this issue of crashing when we use the horizontal flip option.

(Fun part, two video I saw on the web, the guys were explaining your tool but as they knew that if they flip that will crash, they avoid to show it in they video when it is obvious that it would fit perfectly in their tutorial 😂)

Reproduce:
1. Install OBS last version 25
2. Install  Virtual Cam last version https://github.com/CatxFish/obs-virtual-cam/releases/tag/2.0.4
3. Click continue until they are install
4. Go in Virutal Cam in OBS
5. Click on Horizontal
6. Start Virtual Cam
And the error message appear.
(Window 10 (18362)

I will try on my other PC to check it is not something that I do wrong. 

Good luck with the issue.
Just wanted to notify you of the situation most of us have.
In hope to help.

May the code be with you.

**Comment by Mixria** [comment]
Remember to search the issues first!
This is the 4'th one to mention the same issue.

This issue is a duplicate of #44

**Comment by Mixria** [comment]
Plz close it to @EloiStree 😜

**Comment by EloiStree** [comment]
@Mixria  Hello. I know it is a duplicate. 
I did it to make a bit of spam ^^. So many people depend of your fix.
PS: Do you have a Paypal me  where I can donate your a beer when you fixe it ?
